use meta_signal_persona::{
    META_PERSONA_INTERFACE_RUST, META_PERSONA_INTERFACE_SOURCE, bootstrap_manifest,
};

#[test]
fn canonical_source_imports_exact_producer_identities_and_keeps_roles_empty() {
    assert!(META_PERSONA_INTERFACE_SOURCE.starts_with(
        "Interface.{1 0 0}\n[signal_persona:lib.[ComponentStatus ComponentHealth ComponentKind ComponentName ComponentDesiredState EngineIdentifier]]"
    ));
    assert!(META_PERSONA_INTERFACE_SOURCE.contains("OwnerRequest.["));
    assert!(META_PERSONA_INTERFACE_SOURCE.contains("OwnerReply.["));
    assert!(META_PERSONA_INTERFACE_SOURCE.contains("Vector<ComponentStatus>"));
    assert!(META_PERSONA_INTERFACE_SOURCE.contains("\n  []\n  []\n  []\n  ["));
    assert!(!META_PERSONA_INTERFACE_SOURCE.contains("LifecycleComponentStatus"));
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    assert!(META_PERSONA_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    for encoded in ["z2VUT8", "z2VYY4", "z2VWYF", "z2VRuG"] {
        assert!(
            META_PERSONA_INTERFACE_RUST
                .contains(&format!("signal_persona::schema::lib::{encoded}"))
        );
    }
    for visible in [
        "OwnerRequest",
        "OwnerReply",
        "EngineStatusReport",
        "EnginePhase",
    ] {
        assert!(!META_PERSONA_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
        assert!(!META_PERSONA_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
    }
    assert_eq!(bootstrap_manifest::DECLARATION_SEATS.len(), 55);
}

#[test]
fn historical_source_directory_is_absent() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    assert!(!root.join("schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
}
