// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VZ3j {z2VW5r ,} 
pub enum z2VZxR {z2VWVX , z2VTxz , z2Vb1W , z2VRPX , z2VWrt ,} 
pub struct z2Vc9S {
    pub field_0: z2VTEB,
    pub field_1: z2VZxR,
    pub field_2: Vec<signal_persona::schema::lib::z2VWYF>,
}
pub enum z2VRsY {z2Vbif , z2VT8r , z2VW6b ,} 
pub struct z2VLKz {
    pub field_0: signal_persona::schema::lib::z2VRuG,
    pub field_1: z2VM9u,
    pub field_2: z2VZxR,
}
pub struct z2VX4Y(Vec<z2VLKz>);
impl z2VX4Y {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VLKz>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VLKz> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VLKz> {
        self.0
    }
}
pub struct z2VdPy {
    pub field_0: signal_persona::schema::lib::z2VUT8,
    pub field_1: z2VSDb,
}
pub struct z2VRvK ( z2VM9u ,) ;
pub struct z2VWoB {
    pub field_0: signal_persona::schema::lib::z2VRuG,
    pub field_1: z2VPDR,
}
pub struct z2VN6Q {
    pub field_0: z2VM9u,
    pub field_1: z2VRsY,
}
pub enum z2VPDR {z2VNpg , z2Vb1E , z2Vevx ,} 
pub enum z2VSDb {z2VWxB , z2VWwK ,} 
pub struct z2VWds(signal_persona::schema::lib::z2VUT8);
impl z2VWds {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_persona::schema::lib::z2VUT8) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_persona::schema::lib::z2VUT8 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_persona::schema::lib::z2VUT8 {
        self.0
    }
}
pub enum z2Vddz {
    z2VWT8(signal_persona::schema::lib::z2VRuG),
    z2VaMT(z2VWds),
    z2VUcG(z2VRvK),
    z2VauG(z2VU6S),
    z2VZjS(z2VKpw),
}
pub enum z2VTjj {z2VMmu ,} 
pub struct z2VM9u(std::string::String);
impl z2VM9u {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VTEB(u64);
impl z2VTEB {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VW6f {
    z2VaJm(z2Vees),
    z2VV4U(z2VWoB),
    z2VWUX(z2VX4Y),
    z2VaL5(signal_persona::schema::lib::z2VUT8),
    z2VdNk(z2Vc9S),
    z2VX3m(z2VaQD),
    z2VMK9(z2VdPy),
    z2VUza(z2VN6Q),
    z2VWh7(signal_persona::schema::lib::z2VWYF),
    z2VPwy(signal_persona::schema::lib::z2VRuG),
}
pub struct z2VKpw(signal_persona::schema::lib::z2VUT8);
impl z2VKpw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_persona::schema::lib::z2VUT8) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_persona::schema::lib::z2VUT8 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_persona::schema::lib::z2VUT8 {
        self.0
    }
}
pub enum z2VU6S {
    z2VdNo(signal_persona::schema::lib::z2VUT8),
    z2Vbns(z2VTjj),
    z2VeVb(z2VZ3j),
}
pub struct z2Vees {
    pub field_0: signal_persona::schema::lib::z2VUT8,
    pub field_1: signal_persona::schema::lib::z2VYY4,
}
pub struct z2VaQD {
    pub field_0: signal_persona::schema::lib::z2VRuG,
    pub field_1: z2VM9u,
}
